"""drop inert notification_mode columns

Revision ID: 7f9945c67957
Revises: 27e16aa846d0
Create Date: 2026-07-17 04:55:11.383769
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9945c67957'
down_revision: Union[str, None] = '27e16aa846d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'renotify_enabled')
    op.drop_column('alert_rules', 'notification_mode')
    op.drop_column('alert_templates', 'default_notification_mode')
    op.drop_column('alert_templates', 'locks_notification_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_templates', sa.Column('locks_notification_mode', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('alert_templates', sa.Column('default_notification_mode', sa.VARCHAR(length=10), server_default=sa.text("'stateful'::character varying"), autoincrement=False, nullable=False))
    op.add_column('alert_rules', sa.Column('notification_mode', sa.VARCHAR(length=10), server_default=sa.text("'stateful'::character varying"), autoincrement=False, nullable=False))
    op.add_column('alert_rules', sa.Column('renotify_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
